import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Oswald } from "next/font/google";
import Navbar from "./components/Navbar";
const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen h-auto min-h-screen">
      <body className={`${oswald.className} h-auto`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
